- name: add sssh key for hadoga
  authorized_key:
    user: hadoga
    key: "ssh-rsa      AAAAB3NzaC1yc2EAAAADAQABAAACAQD1oOHGfXE5bEKIGZLgzcfjfs8lD7dDULfuAh5qaiyM2sR3QhRrzh5SIwUMC7oimtzV9+si4gCfqsPFlb8zJZBVhWOuJ928/r6r7EqtzfOijyuPZMduLbz0IG8jGwx8xFfwWoZzm4g6G1SHGiW5OM+ja/iLIAYo/ViORWvbbFLWVIjwDK7+eaevOH2TRpMpnLEufSvZxPwTy5kSmdEVO1Ua0ClLUw0b/8FYcHH1Nd0pUX2o7juafDq8RKTmuQOp8BmsHwsWSZi2Uz1647BmcFLyKQcJFO3/vIMcT3+DkCYdgrJh0yg24trwtyPzFVA2mCj9RkP2qi4AW5B2QaZvDZB4S/FI2OYPPGep7AkWwV7rlx14cXjcyTZybOLB9xyCYm/Ov2bIO3L882zKLQ827/5h121HnmR7Porb3sSjOWzBY40pW+v84eaS74SMKBOhAC6cQ8cD/H3hLbD/G5scXmsGSkbBmM7ixBLiER3UoDcJO6jnl7CS2hqX0DCKGs1qxaUYiZVQLCJ2lTy2YSZCU/A7iGbtCaXK5rRwml7FQmNJRfQ0BfkYLmLpyQ+To9fb6I76rxHl/3+5n8ghgPaCChJ++8Gke03CqEKA4sc8Pacq/H7Gt1hrOIrj0QTUuhiY+dPWfXmHikRwzy68yjLCz1PEvn5AI1HbfVS64jO+VjwO3Q== ha535@GVJGH9252G
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCegoBi8j9cTwVjM3GIdaaxJBR0d0F/7MAjwbRK7i+r7UayonlQA37jg2SwrMXhx/14WLrdmOOouSAgsN703+3w/0AxAfCXeo03bz/jHKHzcvBkk16LPrd3XS6lgld3zk2HvyZJLFOQX66fs+pkie43c6jpPQp/djGrEj8PoVfsTYUyY/OXbUaX7s0T4rCul9Uijfw1S/7BcDf7KKYXK90KuspITRYKv3eivq/kSkSBLz9ofJJQJ7gkWLoyWbxCDEi8jRicCMLPo36qPLd50c8hcwlcX/9/Jq05VxNQhzhgtckFsQaYjpRfmKwg/A4ArFRel1mF757wN9E7zBU6ZDPMAFD5QMQVte/iKiKxwLBd0yND75ZquLZYwKm78jUt7ebSEJhCUWPx7fmPXsrtFIMjPEEy7u2EGt9yCKD1PvqGJRQJ4Qaf9tt2Xc2ltchWdT/BrWfpGKhSZb+7Y4Pj5b7d3PwgfS9HaeqhK4EjEaZBgbhudbrt8lFNocWBKvw0qak= haruna.umar.adoga@gmail.com "

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

- name: create password for user hadoga