---
- hosts: all
  become: yes
  tasks:

  - name: Remove packages
    dnf:
      name:
        - httpd
        - autofs
        - nfs-utils
        - terraform
        - tuned
        - container-tools
        - samba
      state: absent
