---
- hosts: all
  become: true
  pre_tasks:

  - name: update all RedHat/Rocky repo
    tags: always
    dnf: 
      name: "*"
      state: latest
    when: ansible_distribution in "RedHat,Rocky"

  - name: update all Ubuntu packages
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base
- hosts: storage_servers
  become: true
  roles:
    - storage_servers

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: compute_servers
  become: true
  roles:
    - compute_servers
- hosts: workstations
  become: true
  roles:
    - workstations
    