---
- hosts: all
  become: true
  pre_tasks:

  - name: update all RedHat/Rocky repo
    tags: always
    dnf: 
      name: "*"
      state: latest
      security: yes
    when: ansible_distribution in "RedHat,Rocky"

  - name: update all Ubuntu packages
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  roles:
    - base
- hosts: storage_servers
  become: true
  roles:
    - storage_servers

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: databases
  become: true
  roles:
    - databases

#- name: Import pre-hook 
#  import_playbook: roles/web_servers/hooks/pre.yml 

#- name: Imort post-hook
#  import_playbook: roles/web_servers/hooks/post.yml 

