---
- hosts: all
  become: true
  pre_tasks:

  - name: Enable ntp synchronisation 
    command: timedatectl set-ntp true
    changed_when: false 

  - name: Set system timezone to Europe/London
    command: timedatectl set-timezone Europe/London
    changed_when: false

  - name: update all RedHat/Rocky repo
    tags: always
    dnf: 
      name: "*"
      state: latest
      security: yes
    when: ansible_distribution in "RedHat,Rocky"

  - name: update all Ubuntu packages
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base
    - ntp
- hosts: storage_servers
  become: true
  roles:
    - storage_servers

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: databases
  become: true
  roles:
    - databases

