---
- hosts: all
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update dnf cache if needed.
      ansible.builtin.dnf:
        name: "*"
        state: latest
    
    - name: Install EPEL Repo
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: Import Remi GPG key
      ansible.builtin.rpm_key:
        key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2018
        state: present

    - name: Install httpd
      ansible.builtin.dnf:
        name: httpd
        state: present


    - name: Add remi repo for Php
      ansible.builtin.dnf:
        name: "https://rpms.remirepo.net/enterprise/remi-release-9.rpm"
        state: present
        disable_gpg_check: true

  handlers:
    - name: restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted

  tasks:
    - name: Get software for dnf repo management
      ansible.builtin.dnf:
        name:
          - python3-dnf
          - python3-pycurl

    - name: Enable PHP 8.2 module
      ansible.builtin.command:
        cmd: dnf module reset php -y
      changed_when: false

    - name: Enable PHP 8.2 from Remi
      ansible.builtin.command: dnf module enable php:remi-8.2 -y
      changed_when: false

    - name: Remove Maria-db
      ansible.builtin.shell:
        cmd: dnf remove -y 'mariadb*' && dnf clean all

    - name: Install Apache, MySQL, PHP, and dependencies
      ansible.builtin.dnf:
        state: present
        name:
          - acl
          - git
          - unzip
          - sendmail
          - httpd
          - php-common
          - php-cli
          - php-gd
          - mysql-server


    - name: Make sure firewalld is enabled and running
      ansible.builtin.shell:
        cmd: systemctl start firewalld && systemctl enable firewalld
        

    - name: Add httpd to firewall 
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: "{{ firewalld_state }}"
      notify: restart httpd

    - name: reload the firewall
      ansible.builtin.shell:
        cmd: firewall-cmd --reload
      notify: restart httpd


    - name: download/upload index.html file to web server
      ansible.builtin.get_url:
        url: https://harunaadoga.github.io/index.html
        dest: /var/www/html/
      notify: restart httpd

- hosts: storage
  become: true
  tags: storage nfs smb
  
  tasks:

    - name: Install nfs and smb
      ansible.builtin.dnf:
        name: 
          - nfs-utils
          - samba
        state: latest

    - name: Ensure nfs and smb are started and enabled
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - smb
        - nfs-server

    - name: Add rpc-bind, mountd and nfs to firewalld
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: true
      loop:
        - rpc-bind
        - mountd
        - nfs

    - name: Reload firewalld for changes to take effect
      ansible.builtin.shell:
        cmd: firewall-cmd --reload
