---
- hosts: all
  become: yes 
  tasks:

  - name: Update all servers 
    tags: always 
    dnf: 
      name: "*"
      state: latest 
    when: ansible_distribution in "RedHat,Rocky"
  
  - name: Install mariadb
    tags: db
    dnf:
      name: 
        - mariadb
        - mariadb-server
      state: latest 
  
  - name: Enable and start mariadb
    tags: always
    service:
      name: mariadb
      enabled: yes
      state: started



