---

#target login nodes
- hosts: login
  become: yes
  pre_tasks:
  
  - name: Update all packages
    tags: always
    dnf:
      name: "*"
      state: latest

  - name: Install httpd, git, vim and postfix  packages
    tags: httpd,git,postfix
    dnf:
      name:
        - httpd
        - git
        - vim
        - postfix
      state: latest
    when: ansible_distribution in ["Rocky", "RedHat"]

  - name: Enable web server and start
    service:
      name: httpd
      enabled: yes
      state: started


# target compute  servers 
- hosts: compute
  become: yes
  tasks:

  - name: install tuned 
    tags: tuned,ethtool
    dnf:
      name: 
        - tuned
        - ethtool
      state: latest 
  - name: enable and start tuned
    service:
          name: tuned 
          enabled: yes 
          state: started


#target storage servers
- hosts: storage
  become: yes
  tasks:

  - name: Install nfs,samba,autofs and conainers 
    tags: autofs,samba,nfs
    dnf:
      name:
        - nfs-utils
        - samba
        - autofs
        - container-tools
      state: latest

  - name: Enable and start podman 
    service:
      name: podman
      enabled: yes
      state: started
        




