---
- hosts: staging-hpc
  name: Setup Apache Webserver
  become: true

  tasks:
    - name: Install Apache Web Server
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start and Enable Apache Web Server
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
    
    - name: Permit HTTP traffic via Firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
        offline: true

    - name: Reload Firewalld Service 
      ansible.builtin.service:
        name: firewalld
        daemon-reload: true

    - name: Copy Web Content to Servers
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: files/index.html
          dest: /var/www/html
