- name: Install httpd and php  packages
  tags: httpd,php
  dnf:
    name:
       - "{{ web_package_name }}"
       - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution in ["Rocky", "RedHat"]
  
- name: Change default httpd port 80 to 88 TCP
  tags: httpd,port
  lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: "^Listen"
      line: Listen 88
  notify: restart_httpd

- name: Add new httpd port to SELINUX and notify handler to restart httpd
  shell:
    cmd: semanage port -a -t http_port_t -p tcp 88
  notify: restart_httpd

- name: Add TCP port 88 to the firewalld 
  shell:
    cmd: firewall-cmd --add-port 88/tcp --permanent; firewall-cmd --reload 
  notify: restart_httpd 
  
- name: copy web files to server 
  tags: httpd, copy
  copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- name: Import pre-hook 
  import_tasks: roles/web_servers/hooks/pre.yml 

- name: Imort post-hook
  import_tasks: roles/web_servers/hooks/post.yml 
