---
- hosts: prod
  become: yes
  tasks:
  
  - name: Update all packages
    dnf:
      name: "*"
      state: latest

  - name: Install needed packages
    dnf:
      name:
        - httpd
        - nfs-utils
        - autofs
        - git
        - vim
      state: latest
    when: ansible_distribution in ["Rocky", "RedHat"]

  - name: Enable web server and start
    service:
      name: httpd
      enabled: yes
      state: started


  


