---
- name: Install and start ntp on all servers
  become: yes
  hosts: all
  tasks:
    - name: Install NTP server/service
        dnf:
          name: chrony
          state: installed

    - tasks:
      name: Start NTP service
      dnf:
        name: chrony
        state: started 
