---
- name: Install and start ntp on all servers
  become: yes
  hosts: all
  tasks:
    - name: Install NTP server/service
      dnf:
        name: chrony
        state: installed

    - name: Make sure the chronyd service is started if not already
      service:
        name: chronyd
        state: started 
