---
- name: Playbook to update all servers
  hosts: all
  become: yes
  tasks:
    
    - name: Patch all RHEL servers
      dnf:
        name: "*"
        state: latest
        autoremove: no
    
    - name: Install mariadb client
      dnf:
        name: mariadb
        state: present
    
    - name: install mariabdb server
      dnf:
        name: mariadb-server
        state: present
    - name: Start mariabd
      systemd_service:
        name: mariadb
        state: started
        daemon_reload: true
        enabled: yes
