- name: Install nfs,samba,autofs and conainers 
  tags: autofs,samba,nfs
  dnf:
    name:
       - nfs-utils
       - samba
       - container-tools
    state: latest
  notify:
    - restart_nfs 
    - start_podman
    - start_samba
 