web_package_name: httpd
web_service: httpd
php_package_name: php
ssh_users: "student hadoga"
ssh_template_file: sshd_config_redhat.j2
tuned_service: tuned
autofs_service: autofs 
nfs_service: nfs-server 
db_service: mariadb 
db_server: mariadb-server
container_service: podman
samba_service: samba 